services:
  glances:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      GLANCES_OPT: "-C /glances/conf/glances.conf -w"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./glances.conf:/glances/conf/glances.conf"
    networks:
      - proxy-nw
    pid: "host"
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.glances.rule=Host(`glances.local`)"
      - "traefik.http.services.glances.loadbalancer.server.port=61208"

networks:
  proxy-nw:
    external: true