services:
  gitea:
    image: gitea/gitea:1.18.1
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__server__ROOT_URL=http://gitea.local/ 
    restart: always
    networks:
      - proxy-nw
    volumes:
      - gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      # - "3000:3000"
      - "222:22"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gitea.rule=Host(`gitea.local`)"
      - "traefik.http.services.gitea.loadbalancer.server.port=3000"

networks:
  proxy-nw:
    external: true

volumes:
  gitea:
    driver: local